import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  apiSidebar: [
    {
      type: "category",
      label: "Workflows",
      link: { type: "generated-index", title: "Workflows API" },
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

export default sidebars;
